import { get_data } from "@/components/helpers/supabase";
import { IData } from "@/components/mock/mock_data";
import { PaginationItems, PaginationNextTrigger, PaginationPrevTrigger, PaginationRoot } from "@/components/ui/pagination";
import { Container, Flex, Heading, HStack, IconButton, Stack, Table } from "@chakra-ui/react";
import Head from "next/head";
import { useEffect, useState } from "react";
import { FaPencilAlt } from "react-icons/fa";
import { Toaster, toaster } from "@/components/ui/toaster"
import { Spinner } from "@chakra-ui/react"

export default function Home() {
  const [page, setPage] = useState(1)
  const [data, setData] = useState<IData[]>([])

  useEffect(() => {
    (async () => {
      const { data, error } = await get_data();

      if (error)
        console.error({ error })

      if (data)
        setData(data)
    })();
  }, [])

  return (
    <>
      <Head>
        <title>Dashboard | Halal Bihalal 2025</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      {data.length <= 0 && (
        <Flex h="100vh" justifyContent="center" alignItems="center">
          <Spinner size="md" />
        </Flex>
      )}

      {
        data.length > 0 && (
          <Container mt={10}>
            <Heading mb={5}>Daftar Peserta</Heading>
            <Table.Root size="sm">
              <Table.Header>
                <Table.Row>
                  <Table.ColumnHeader>No.</Table.ColumnHeader>
                  <Table.ColumnHeader>Nama</Table.ColumnHeader>
                  <Table.ColumnHeader>Phone</Table.ColumnHeader>
                  <Table.ColumnHeader>Email</Table.ColumnHeader>
                  <Table.ColumnHeader>Department</Table.ColumnHeader>
                  <Table.ColumnHeader>Shirt Size</Table.ColumnHeader>
                  <Table.ColumnHeader>Actions</Table.ColumnHeader>
                </Table.Row>
              </Table.Header>
              <Table.Body>
                {data.map((item, index) => (
                  <Table.Row key={item.phone}>
                    <Table.Cell>{++index}</Table.Cell>
                    <Table.Cell>{item.name}</Table.Cell>
                    <Table.Cell>{item.phone}</Table.Cell>
                    <Table.Cell>{item.email}</Table.Cell>
                    <Table.Cell>{item.department}</Table.Cell>
                    <Table.Cell>{item.shirt_size}</Table.Cell>
                    <Table.Cell>
                      <IconButton aria-label="Edit" onClick={() => {
                        toaster.create({
                          description: "Edit",
                          type: "info",
                          duration: 2000
                        })
                      }}>
                        <FaPencilAlt />
                      </IconButton>
                    </Table.Cell>
                  </Table.Row>
                ))}
              </Table.Body>
            </Table.Root>

            <Stack>
              <PaginationRoot
                count={10}
                pageSize={2}
                defaultPage={page}
                onPageChange={(e) => {
                  setPage(e.page)
                }}
              >
                <HStack>
                  <PaginationPrevTrigger />
                  <PaginationItems />
                  <PaginationNextTrigger />
                </HStack>
              </PaginationRoot>
            </Stack>
            <Toaster />
          </Container >
        )
      }
    </>
  )
}